### ISSUE TITLE
Move message updates to SSE model

### ISSUE THREAD

**Issue by kevinharv** [MagnusChase03/DiscordClone#34]
Implement server-side events for updating the client with new messages.

- [x] SERVER - post message updates
- [x] CLIENT - listen for message updates

**Comment by MagnusChase03** [comment]
More information about server side events can be found [here](https://masteringjs.io/tutorials/express/server-sent-events)

**Comment by MagnusChase03** [comment]
Done

**Comment by kevinharv** [comment]
I want to cry.
